Bogdanp/dramatiq

- docs/source/advanced.rst
- docs/source/changelog.rst
- docs/source/global.rst
- docs/source/motivation.rst
- docs/source/reference.rst
- dramatiq/message.py
- dramatiq/middleware/middleware.py
- dramatiq/rate_limits/backends/__init__.py
- dramatiq/rate_limits/backends/memcached.py
- dramatiq/rate_limits/backends/redis.py
- dramatiq/rate_limits/backends/stub.py
- dramatiq/results/__init__.py
- dramatiq/results/backend.py
- dramatiq/results/backends/__init__.py
- dramatiq/results/backends/memcached.py
- dramatiq/results/backends/redis.py
- dramatiq/results/backends/stub.py
- dramatiq/results/errors.py
- dramatiq/results/middleware.py
- setup.py
- tests/conftest.py
- tests/test_bucket_rate_limiter.py
- tests/test_concurrent_rate_limiter.py
- tests/test_results.py
- tests/test_window_rate_limiter.py
> Add result backends

- docs/source/changelog.rst
- docs/source/global.rst
- docs/source/reference.rst
- dramatiq/__init__.py
- dramatiq/broker.py
- dramatiq/encoder.py
- dramatiq/message.py
- tests/test_encoders.py
Addresses #17.  
I'm going to let this sit for a bit.
cc. @jssuzanne @cailiang9
> feature: add support for pluggable message encoders

- dramatiq/broker.py
- dramatiq/brokers/stub.py
- dramatiq/common.py
- tests/test_actors.py
- tests/test_stub_broker.py
Cherry picked from the pika 0.12 branch
> fix(stub): make join() more reliable

- docs/source/changelog.rst
- dramatiq/brokers/redis.py
- dramatiq/worker.py
- tests/conftest.py
> fix(worker): handle acknowledgement failures gracefully

- CONTRIBUTORS.md
- dramatiq/cli.py
return RET_KILLED when subprocess is terminated by unhandlable signal (like SIGKILL)
fixes https://github.com/Bogdanp/dramatiq/issues/333
> return RET_KILLED when subprocess is terminated by unhandlable signal

- dramatiq/middleware/time_limit.py
See also issue #379. @Bogdanp, please let me know if I need to update the docs in some other place as well.
> Update time_limit parameter doc for TimeLimit middleware.

- dramatiq/encoder.py
> encoder: convert decoding errors into DecodeErrors

- dramatiq/middleware/shutdown.py
- tests/middleware/test_shutdown.py
> Add gevent support to the Shutdown middleware

- dramatiq/brokers/redis.py
- dramatiq/middleware/shutdown.py
https://docs.python.org/3.9/library/stdtypes.html#frozenset.discard
> use set.discard to remove item

- dramatiq/cli.py
> Make sure 'running' is assigned before reference

- dramatiq/brokers/stub.py
> Add guard clause to stub.py

- .github/ISSUE_TEMPLATE.md
```diff
- succint
+ succinct
```
> Fix a typo

- CONTRIBUTORS.md
- docs/source/sitemap.py
- dramatiq/broker.py
- dramatiq/cli.py
- dramatiq/encoder.py
- dramatiq/results/backends/stub.py
- mypy.ini
- tests/middleware/test_shutdown.py
- tests/test_cli.py
* py.typed mark as required by [PEP-561](https://peps.python.org/pep-0561/)
* add mypy.ini config
* fix JSONEncoder error handling
* some mypy error fixes
* some isort error fixes
Closes #305
> typing: improved mypy support

- .github/workflows/push.yml
- setup.py
- tox.ini
> Add python3.11 build support, drop python3.6

- dramatiq/message.py
- tests/test_messages.py
Thanks to @jurrian for identifying the issue in Bogdanp/django_dramatiq#143
> message: add namedtuple methods for backwards-compat

- docs/source/motivation.rst
Hi @Bogdanp,
Thanks for maintaining this wonderful package. I just wanted to share our little 3rd party library with you and other Dramatiq users.
Cheers!
Joe
> Add 3rd-party reference for cron tasks

- CONTRIBUTORS.md
- dramatiq/broker.py
> chore: add type hint to global dramatiq.broker.global_broker variable

- docs/source/cookbook.rst
- docs/source/reference.rst
As per comment https://github.com/Bogdanp/dramatiq/pull/566#issuecomment-1685892964
> doc: minor improvements of Cookbook and Reference doc pages

- CONTRIBUTORS.md
- docs/source/changelog.rst
- dramatiq/cli.py
- dramatiq/watcher.py
> Watch patterns

- setup.py
Seems this bit was missed in https://github.com/Bogdanp/dramatiq/pull/587.
> Update python_requires in setup.py

- dramatiq/results/middleware.py
> Result middleware: consider message options before actor options

- dramatiq/message.py
> fix: message can be covariant in result type

- docs/source/advanced.rst
- docs/source/cookbook.rst
- docs/source/global.rst
> Add documentation of asyncio support

- docs/source/advanced.rst
- docs/source/reference.rst
- dramatiq/brokers/rabbitmq.py
I figured this would be good to have for visibility/awareness of these.
> Add documentation for the environment variables dramatiq uses

- dramatiq/middleware/age_limit.py
- dramatiq/middleware/asyncio.py
- dramatiq/middleware/group_callbacks.py
- dramatiq/middleware/middleware.py
- dramatiq/middleware/prometheus.py
- dramatiq/middleware/retries.py
- dramatiq/middleware/shutdown.py
- dramatiq/middleware/time_limit.py
Closes #521
Following up on comment https://github.com/Bogdanp/dramatiq/pull/731#issuecomment-3069279831. Alas, I am not familiar enough with Sphinx to work with the `NameError` caused by the missing (typing only) imports (perhaps related issue https://github.com/sphinx-doc/sphinx/issues/13137).
> Improve typing coverage of middleware classes

- .github/ISSUE_TEMPLATE/bug_report.md
To increase the chances bug reports have useful info for us
> Update bug_report.md issue template

- .github/workflows/push.yml
- .github/workflows/release.yml
- setup.py
- tox.ini
* Add 3.14 classifier
* Add 3.14 to test matrix
> Test and declare support for python 3.14

- CONTRIBUTORS.md
- dramatiq/brokers/redis.py
- dramatiq/rate_limits/backends/redis.py
- dramatiq/results/backends/redis.py
- setup.py
> Replace StrictRedis with Redis and bump redis version to >=4
