Bogdanp/dramatiq

CONTRIBUTORS.md
dramatiq/rate_limits/backend.py
dramatiq/rate_limits/backends/memcached.py
dramatiq/rate_limits/backends/redis.py
dramatiq/rate_limits/backends/stub.py
dramatiq/rate_limits/window.py

Change the `WindowRateLimiter` to pass a callable to `incr_and_sum` so
that during atomic increments the time windows can be recomputed in the
event of a lock.
This breaks the API because we change `incr_and_sum`'s `keys` arg to
a callable. We keep backwards compatibility by checking if `keys` is
callable and calling it on each use.

Recompute keys in atomic incr with sliding window

---

docs/source/changelog.rst
docs/source/guide.rst
docs/source/troubleshooting.rst
dramatiq/broker.py
dramatiq/brokers/stub.py
dramatiq/worker.py
tests/test_stub_broker.py

Closes #195.  This makes it possible to receive the original exception
inside the joining thread.

feat(stub): add fail_fast param to StubBroker.join

---

CONTRIBUTORS.md
dramatiq/composition.py
dramatiq/middleware/pipelines.py
tests/test_composition.py

Fixes https://github.com/Bogdanp/dramatiq/issues/206.
The delays of messages in the pipeline were ignored, only the `delay` parameter of pipeline's `run` method was taken into consideration.
This PR fixes the handling of delay parameters of messages in a pipeline (first and all following). In addition in alters the behavior of the `delay` parameter of pipeline's `run` method, so that:
1. If there's either a delay specified for the first message or there's a delay specified in pipe run invocation, take the one that's present.
2. If they are both present, take the one that has higher value.

Fixing delays of messages in a pipeline

---

dramatiq/cli.py

This PR adds a `skip-logging` flag to the CLI invocation arguments.
This came from wanting to adjust the LOGFORMAT of Dramatiq's log messages. I wanted to eliminate the `[Thread-X]` bit and modify the order of things to better match the rest of my system
`logging.basicConfig` is a no-op if the root logger has handlers added to it, but due to the fact that the Dramatiq CLI is invoked before any of my code, there is no way to beat that to the punch.
So instead I opted to add a `--skip-logging` flag that will prevent `basicConfig` from ever happening. This allows the end user to define the handlers and whatnot without having to undo anything done by Dramatiq's bootup sequence.
Hopefully this is something that is worth merging into the project.

Add a skip-logging flag to the CLI

---

CONTRIBUTORS.md
dramatiq/cli.py

This is a fix for https://github.com/Bogdanp/dramatiq/issues/260
I have verified using the reproducible steps in the issue, that this patch prevents dramatiq hanging when `pipe.close()` raises an OSError.

Prevent hang when pipe already closed

---

dramatiq/brokers/redis.py

I forgot that removing a key from a set that doesn't have that key raises a KeyError.

[Redis] Fix key error in queued message tracking

---

dramatiq/composition.py
dramatiq/middleware/__init__.py
dramatiq/middleware/group_callbacks.py
tests/test_composition.py

feat(composition): add support for group completion callbacks

---

tests/test_rabbitmq.py
tests/test_redis.py

There is a small typo in tests/test_rabbitmq.py, tests/test_redis.py.
Should read `success` rather than `sucess`.

docs: Fix simple typo, sucess -> success

---

docs/source/changelog.rst
docs/source/reference.rst
dramatiq/broker.py
dramatiq/results/__init__.py
dramatiq/results/backend.py
dramatiq/results/backends/redis.py
dramatiq/results/errors.py
dramatiq/results/middleware.py
dramatiq/results/result.py
dramatiq/worker.py
tests/test_results.py

Closes #156.  This should be both forwards (mostly) and backwards-compatible.  The only weirdness here is the interaction of failures with retries, but I think I'm fine with leaving the burden on the user to figure that out.

results: store actor failures

---

docs/source/guide.rst

I have changed it to be `13047` because that what example tells us it is.
This way one can more easily use "find on this page" to get the idea.

fix(docs): makes `[dramatiq.MainProcess]` pid consistent

---

docs/source/advanced.rst

Clarify that a `redis_message_id` must be set in the `options` field of the message and that that ID is the one used in the `HSET` and `RPUSH`.

Minor change to the docs on enqueuing Redis messages from other languages.

---

CONTRIBUTORS.md
docs/source/installation.rst
dramatiq/cli.py

Fixes #326
I'm not sure if / how should this be tested. Currently all cli test are skipped on windows.

Raise an error if watch is used on an unsupported system.

---

.github/workflows/push.yml
CONTRIBUTORS.md
tox.ini

Closes #318.
I also did some tox cleanup so that we wouldn't need to install libmemcached-dev to run `tox -e lint`.
The Windows changes are because of https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew

ci: Add Python 3.8

---

dramatiq/results/backends/redis.py

As I am moving some existing code into workers I want my backtraces to be raised as if they were in process.
A quick hack with tblib seems to work fine, but I have to overwrite the complete `RedisBackend.get_result`. If `RedisBackend.unwrap_result` would exist I could simply do something like this:
```python
class ExceptionPicklingRdisBackend(dramatiq.results.backends.RedisBackend):
def store_exception(self, message, exception: Exception, ttl: int) -> None:
tblib.pickling_support.install()
message_key = self.build_message_key(message)
return self._store(message_key, exception, ttl)
def unwrap_result(self, res):
tblib.pickling_support.install()
if isinstance(res, BaseException):
raise res
return super().unwrap_result(res)
```

res: allow to overwrite unwrap_results()

---

.github/workflows/push.yml

This addresses broken tests in the CI env by using a native port of
memcached for the test suite... I'm not sure if it's crashing, or unable
to handle the load from the test suite, but the native copy seems to
do fine.
Fixes https://github.com/Bogdanp/dramatiq/issues/370.

ci: fix memcached for windows

---

dramatiq/results/middleware.py
tests/test_results.py

This avoids the Results middleware's warning about a return value that
isn't stored when piped messages are used.
The actor's warning about returning results already has this behavior,
but it felt like we should avoid the log message for piped messages w/
Results middleware too.

logging: omit result warning with piped messages

---

docs/source/changelog.rst
dramatiq/brokers/rabbitmq.py
dramatiq/worker.py

rabbitmq: ensure deleting `connection` and `channel` closes each

---

docs/source/cookbook.rst

Sorry for this very tiny PR.
Today I started learning dramatiq and I found an issue in the sample code in [the cookbook](https://dramatiq.io/cookbook.html).
```
if __name__ == "__main__":
identity.send_with_options(
args=(42,)
on_failure=print_error,
on_success=print_result,
)
```
A comma is missing after `args=(42,)`. This PR fixes the issue.

docs: add a missing comma in the sample code

---

docs/source/advanced.rst

The `dramatiq:` prefix was missing.

fix missing prefix in Redis list and hash name

---

dramatiq/broker.py

I found this change rather useful when debugging custom middlewares.

Log middleware type when callback execution fails.

---

dramatiq/middleware/threading.py
tests/middleware/test_threading.py

Fix AsyncExc thread_id ctype for python >= 3.7

---

.github/workflows/push.yml
docs/source/changelog.rst
dramatiq/brokers/redis/dispatch.lua

redis: only requeue existing messages for dead workers

---

dramatiq/middleware/retries.py
tests/test_actors.py

Fixes #388 
Tests added to test_actors.py for small diff. 
I have a separate branch on top of this locally that refactors all Retries tests from test_actors.py into a new test_retries.py module under tests/middleware. I can make a PR for that refactoring as well if desired.

Allow actors and messages to specify 0 backoff

---

setup.py

redis-py recently released version 4.0 which adds support for a few new APIs (in my case, I'm hoping to use some of the new Redis streams commands that are not available on 3.x). This change allows using Dramatiq with Redis 4.x.
I've tested this locally and with the CI workflow and things seem to work fine.
Looking through the list of [breaking changes](https://github.com/redis/redis-py/releases/tag/v4.0.0b1) there doesn't seem to be anything that directly impacts Dramatiq. The only thing tangentially related is [some changes](https://github.com/redis/redis-py/issues/589) to how URL encoded parameters in Redis URLs are handled.

Allow using Redis 4.x. as a dependency.

---

CONTRIBUTORS.md
dramatiq/actor.py
dramatiq/brokers/rabbitmq.py
dramatiq/brokers/redis.py
dramatiq/rate_limits/backends/memcached.py
dramatiq/rate_limits/backends/redis.py
dramatiq/results/backends/memcached.py
dramatiq/results/backends/redis.py

Resolves #377 
According to [PEP 484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values), when writing types for `**kwargs` parameters, we're supposed to specify the type for the individual parameters. So when we say that `**options` is a `dict`, we're telling type checkers that _every parameter you pass as an option_ should be a `dict`.
If my understanding is correct, the types of these parameters could really be anything, so I just removed the type annotation entirely.
This cleans up a lot of big ugly warnings in PyCharm at least.

Remove (dict) from **kwargs types

---

dramatiq/cli.py
tests/test_cli.py

Fixes #465
Adds lots of tests for threads and processes that may be affected
depending on when signals are unblocked.

Unblock signals earlier in worker process

---

CONTRIBUTORS.md
dramatiq/compat.py

Some libraries (in my case [playwright](https://github.com/microsoft/playwright-python)) try to access `sys.<stdout|stderr>.closed` which raises an error if run in a Dramatiq actor. This fixes that.
I haven't written any tests because this is such a small change and I do not see any existing tests for `StreamablePipe`. However, let me know if you'd like me to add one.
P.S. I'm really loving Dramatiq! Thank you for all your work

Adds closed attribute to StreamablePipe

---

CONTRIBUTORS.md

This fixes a copy paste issue in the `CONTRIBUTORS.md` giving credit where credit is due 🙌

Correct Contributor Name

---

dramatiq/brokers/redis.py
dramatiq/brokers/redis/dispatch.lua
tests/test_redis.py

This fixes #480 
I'm not sure how to test this, since the race condition is not easy to trigger. @Bogdanp do you have any suggestions?
Also looking at the stub broker it seems that it may have a similar race condition, but I've never triggered a similar issue with it, so I'm not sure if the change (swapping the order or the delay queue and normal one) is needed
https://github.com/Bogdanp/dramatiq/blob/2d0ca2519a0289946337b308e450a915cf5fd869/dramatiq/brokers/stub.py#L153-L164

fix: race condition on join() in the redis broker.

---

CONTRIBUTORS.md
dramatiq/actor.py

`args` is accessed as a tuple, but `*args` must be annotated according to its individual argument types, like `Any` or `Union[str, int]`.
The annotation as it currently stands causes code linter warnings.

Fix an incorrect type annotation

---

dramatiq/broker.py

This change allows users to use Redis when working through the intro video.
Closes #483

Fallback to Redis if RabbitMQ deps aren't installed

---

docs/source/cookbook.rst
docs/source/global.rst
dramatiq/middleware/age_limit.py
dramatiq/results/middleware.py
dramatiq/worker.py
tests/test_results.py

Fixes #440
Stuff SkipMessage exceptions into the message proxy to ensure that
the result is consistent when used in conjunction with the Results
middleware.
Additionally, move the message.fail() call into the SkipMessage
handling to ensure that skipped messages are nack'd rather than
ack'd.
Note that if failing the message is left to the middleware,
then unintentionally omitting message.fail() can lead to no result
ever being stored by the results middleware for the message.
If it should be left to the middleware to decide to fail the skipped
message then it would be more sensible to have fail as the default.
This could be achieved by making the SkipMessage exception take an
optional "fail_message" parameter that defaults to True, and have
the message conditionally fail() inside the …

Stuff SkipMessage and fail skipped messages

---

.github/workflows/push.yml
docs/source/changelog.rst
docs/source/index.rst
docs/source/installation.rst
setup.py

build: drop Python 3.6

---

dramatiq/worker.py
tests/test_concurrent_rate_limiter.py

There are small typos in:
- dramatiq/worker.py
- tests/test_concurrent_rate_limiter.py
Fixes:
- Should read `should` rather than `shoud`.
- Should read `expect` rather than `exepct`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

CONTRIBUTORS.md
dramatiq/results/backends/__init__.py

Defer imports of backend client libraries until the backend is instantiated. This should maintain the existing failure behavior which lazily causes usages of missing backends to fail. However it defers the emission of warnings on unused backends **until** they're instantiated
Addresses https://github.com/Bogdanp/dramatiq/issues/421
This is perhaps somewhat of an suboptimal way of "fixing" the problem, but due to lack of response on the issue, I opted for an option with perhaps the least chance of it breaking existing users, since you expose both RedisBackend/MemcachedBackend throught `__all__` which arguably makes them part of your expected public interface.
I'm happy to adjust to other options if this isn't how you'd ideally fix it.

fix: Avoid warning on missing dependencies when those dependencies are used.

---

dramatiq/actor.py
dramatiq/encoder.py
dramatiq/message.py
dramatiq/middleware/shutdown.py
dramatiq/middleware/time_limit.py
dramatiq/results/backend.py

1. Fix existing type violations reported by mypy.
2. Annotate types for `Actor`, `actor`, and `Message`
3. Use TypeVar with Generic to propagate the return type of the function. For example, if you wrap a function that returns `str`, then mypy will know that calling `Actor` instance also returns `str`.
Something that can be improved later:
1. `Message` is a namedtuple, and so cannot inherit from Generic. It can be solved by using a dataclass instead.
2. Types for arguments of the function can be typed with [Parameter Specification Variables](https://peps.python.org/pep-0612/), but for that, you'll need [typing-extensions](https://pypi.org/project/typing-extensions/) the good news is that it can be static-only dependency by putting it inside of `if TYPE_CHECKING`. But I didn't want to …

Annotate types for Actor and Message

---

dramatiq/composition.py
dramatiq/message.py

The changes in #513 broke tests a bit that relied on Message being a namedtuple, see comment https://github.com/Bogdanp/dramatiq/pull/513#issuecomment-1342164116 by @anton-petrov.
1. Add `pipe_target` into `Message.options` inside of `pipeline` in the reverse order, so that the message dump inside `pipe_target` recursively contains `pipe_target` of the next message.
2. Add `Message.__lt__`, so that messages can be sorted. The sorting order is the same as it was for namedtuple.
3. Make sure `Message.args` is a tuple when restoring from a dump.

Fix tests broken by moving Message to dataclass

---

dramatiq/actor.py

The PR introduces ParamSpec ([PEP 612](https://peps.python.org/pep-0612/)) to type annotate that `Actor.__call__` and similar expect all the same arguments as the wrapped handler function. A few clarifications on the black magic that happening:
1. I import ParamSpec from [typing-extensions](https://pypi.org/project/typing-extensions/) to be compatible with all Python versions.
2. I have this import and ParamSpec definition inside of `if TYPE_CHECKING` block, so dramatiq doesn't depend on typing-extensions at runtime. At static type checking time by mypy, typing-extensions are guaranteed to be available because they are a dependency of mypy (and pyright has their stubs bundled).
3. I added `from __future__ import annotations`, so that imports are lazy. See [PEP …

Use ParamSpec to type check Actor args

---

.github/workflows/release.yml

- release-published triggers a release to PyPI
- the build is done via pypa's `build` which provides a generic build frontend even if the project moves off of setuptools in the future
- upload is done by the pypa-provided github action
References:
- #531 motivated this
- credit to @amureki for the original workflow on which this is modeled

Add a release GHA workflow using 'build'

---

setup.py

I've encountered issue when installing Dramatiq from commit `78f0f8bbd6312ebb0b811f661ef5fe8773107aa3`. 
It turns out that asyncio support was added but module that implements this supports is not included in distribution package. It fixes error `ModuleNotFoundError: No module named 'dramatiq.asyncio'`

build: add missing asyncio module to package

---

docs/source/changelog.rst
dramatiq/watcher.py
setup.cfg
tests/test_watch.py

As of watchdog >= 2.3, file open events on certain platforms are causing an 'opened' event to be delivered.  We should not be restarting the server on these changes, as they can be spammy and disruptive.
I was able to confirm the behaviour by running the tests within a debian-like environment (python slim bullseye); without the fix, the `tests/test_watch.py` would fail for the first test case (the evented observer)
For more context, see discussions here:
- https://github.com/gorakhargosh/watchdog/issues/949
- https://github.com/pallets/werkzeug/pull/2604/files

Don't reload on watchdog 'opened' events

---

dramatiq/brokers/rabbitmq.py
tests/test_rabbitmq.py

When a worker is started, it'll eventually start two consumers: one for reading off the queue and another for reading off the delayed queue. When it starts consuming off the delayed queue, it calls `RabbitmqBroker#consume('queue_name.DQ')`. In turn, `queue_name.DQ` goes through the declare queue initialization which results in its name being added to the `RabbitmqBroker.queues` set. This becomes an issue as later on in commands such as `RabbitmqBroker#flush`, where assumptions are made that only the canonical queue name is present.

Ensure only canonical are added to RabbitmqBroker.queues

---

docs/source/advanced.rst

The format of the link was outdated and lead to a non-existent page

doc: update link to example grafana dashboard

---

dramatiq/composition.py

I noticed that the return value isn’t documented in the API docs [here](https://dramatiq.io/reference.html#dramatiq.group.run) which makes reading [this example](https://dramatiq.io/cookbook.html#groups)
```python
g = group([
frobnicate.message(1, 2),
frobnicate.message(2, 3),
frobnicate.message(3, 4),
]).run()
```
questionable if `run()` wouldn’t return anything.
And while I’m poking some more through the documentation I noticed a few things:
- This line https://github.com/Bogdanp/dramatiq/blob/76578a6ea5017f5a0680279692eee357d7b7f229/docs/source/reference.rst?plain=1#L81 I think could use a `:members:` to document the `get_current_message()` class method which isn’t currently documented [here](https://dramatiq.io/reference.html#dramatiq.middleware.CurrentMessage).
- This line …

doc: mention return value for group.run() methods

---

setup.py

This PR enables support for redis-py 5.0.0.
https://github.com/redis/redis-py/releases

Support redis-py 5

---

CONTRIBUTORS.md
dramatiq/actor.py
tests/test_actors.py

This implements https://github.com/Bogdanp/dramatiq/issues/522 as suggested by @dragonpaw
Support for using `timedelta` for the actor delay was added at the public interface. Alternatively it could have been implemented by switching to timedelta internally and converting to int / float when interfacing with external libraries. This would improve type safety in dramatiq, but it is a more intrusive change.
Based on feedback from this PR I can open a followup to support `timedelta` for timeout args as well.

Add support for timedelta as actor delay

---

CONTRIBUTORS.md
dramatiq/broker.py
dramatiq/composition.py
dramatiq/message.py

These are the proposed changes to address the issue described in: https://github.com/Bogdanp/dramatiq/issues/564
The issue is that the groups and pipelines look for the backend of the default/global broker when getting results, regardless of the broker they were declared with.

Use backend from group/pipeline broker in get_result(s)

---

dramatiq/asyncio.py
tests/middleware/test_asyncio.py

Following up #536 ; it seems that there is no cleanup happening when an asyncio actor is interrupted. It is often important to leave stuff in a consistent state (e.g. releasing a lock) when interrupting an actor.
This does not happen correctly as soon as there is an `await` in the `finally` block.
~I have no clue yet how to approach this issue.~
Redoing the `run_courotine_threadsafe` turned out to be quite cumbersome. So in the end I solved the issue by adding a "done" event and wrapping the coroutine in a `try .. finally`.

Fix “an interrupted (Cancelled) coroutine doesn't cleanup”

---

docs/source/reference.rst

…like they are for other ABCs and e.g. the Rate Limiter itself:
https://github.com/Bogdanp/dramatiq/blob/8e0ced79ee55bd8062063d6274c70bcbf1ce362a/docs/source/reference.rst?plain=1#L154-L158
Probably wouldn’t help much to document the members of the subclasses 🤔

doc: add members documentation to Result middleware, and Results and Rate Limiters backends

---

dramatiq/middleware/prometheus.py

fix: don’t hardcode the temp path for the Prometheus middleware

---

.github/workflows/push.yml
.github/workflows/release.yml
setup.py
tox.ini

Python3.12 has been released and python3.7 has been past end-of-life since 2023-06-27.
This change adds build support for python3.12 and drops build support for python3.7.

Add build support for python3.12, drop python3.7

---

CONTRIBUTORS.md
dramatiq/middleware/current_message.py
tests/middleware/test_asyncio.py

Moved from `locals` to `contextvars` to address issues while running under `AsyncIO`.
Fixes #586

Fix for `current_message` while operating under `AsyncIO`

---

CONTRIBUTORS.md
docs/source/changelog.rst
dramatiq/cli.py

(Apologies for not starting a discussion as requested in contributing guidelines... let's have the discussion here and reject this PR if it doesn't align with your vision.)
Improves the newline handling in log forwarding from workers so that it does not always introduce newlines.
Due to some unknown change in our setup, we started seeing log messages from workers split into multiple lines:
Perhaps we are flushing log message more frequently than expected by dramatiq... and the flushes are not aligned with newlines. 
After some digging, we found that the newlines are inserted by dramatiq here:
https://github.com/Bogdanp/dramatiq/blob/a30b7878c5f7570864b1e056580faecbf2abdad2/dramatiq/cli.py#L322-L338
This code _always_ adds a newline, even if the `rstrip` did not strip one out.
Given the …

Improve handling of newlines in log messages

---

dramatiq/brokers/rabbitmq.py

The version specified in the link to the Pika docs is no longer available.

docs: Fix broken link to Pika connection parameters

---

dramatiq/middleware/middleware.py
dramatiq/worker.py

This allows the middleware to run code in the context of a worker or consumer thread before it enters its run loop. This could be used to set up thread-local resources, or as in the author's case, to get a reference to the thread before it does any work.
This was proposed on the mailing list [0] with Bogdan accepting the idea in principle [1].
[0]: https://groups.io/g/dramatiq-users/topic/105311701
[1]: https://groups.io/g/dramatiq-users/topic/105311701#258

feature: add middleware after_{consumer,worker}_thread_boot hooks

---

dramatiq/brokers/rabbitmq.py
tests/test_rabbitmq.py

The declared rabbitmq queue will be missing sometime, such as deletion by mistake or rabbitmq server failure. So I add some logic to make sure the missing queue to be declared again, as the recent implementation won't auto re-declare the missing queue.
There are two situation to re-declare the missing queue:
- Declare the queue every time when the consumer start.
- Redeclare the queue when queue is found to be missing during enqueue.

fix: detect the missing of rabbitmq queue and redeclare it.

---

CONTRIBUTORS.md
dramatiq/middleware/retries.py
tests/middleware/test_retries.py

For motivation see discussion at 
https://groups.io/g/dramatiq-users/topic/how_to_check_how_long_message/106519634
Retries middleware now records requeue_timestamp on message options in `before_enqueue` function if message failed execution.
Hoped the implementation and tests are up to required standards, if not, let me know what needs to be changed.

Updated Retries middleware

---

dramatiq/asyncio.py
tests/middleware/test_asyncio.py

Noticed this warning while attempting to run the test suite with warnings enabled.
```
tests/middleware/test_asyncio.py::test_event_loop_thread_run_coroutine_interrupted
ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```
This PR makes calls to `.stop()` join the thread and then close the event loop, which resolves the warning above.

Close an asyncio event loop in the test suite

---

tests/conftest.py

Spotted this while attempting to run the test suite locally with warnings enabled.
```
tests/test_cli.py::test_cli_fails_to_start_given_an_invalid_broker_name
tests/test_cli.py::test_cli_fails_to_start_given_an_invalid_broker_instance
tests/test_cli.py::test_cli_fails_to_start_given_an_invalid_nested_broker_instance
/home/kurt/dev/pr-dramatiq/.venv/lib/python3.12/site-packages/_pytest/runner.py:141:
ResourceWarning: unclosed file <_io.FileIO name=12 mode='rb' closefd=True>
```
The three tests listed are the only ones that read from STDOUT pipes; closing the pipe in the pytest fixture is the most reliable way to address this.

Close subprocess STDOUT pipes in the test suite

---

tests/test_rabbitmq.py

I found this while attempting to run the test suite locally with warnings turned on.
```
tests/test_rabbitmq.py:22:
DeprecationWarning: Use RabbitmqBroker with the 'url' parameter instead of URLRabbitmqBroker.
```
As this is a known and expected warning, this PR ensures the test suite catches the `DeprecationWarning`.

Catch an anticipated DeprecationWarning

---

tests/middleware/test_asyncio.py

Spotted this while attempting to run the test suite locally with warnings enabled:
```
tests/middleware/test_asyncio.py::test_event_loop_thread_start_timeout
lib/python3.12/site-packages/_pytest/threadexception.py:77:
PytestUnhandledThreadExceptionWarning: Exception in thread Thread-13
```
The easiest fix is to stop raising an exception in the mock. In addition, since `RuntimeError` may be raised in several ways, I added a `match` argument to the `pytest.raises()` context manager to identify which `RuntimeError` text is expected.
After avoiding that warning, a ResourceWarning popped up:
```
tests/middleware/test_asyncio.py::test_event_loop_thread_start_timeout
lib/python3.12/asyncio/base_events.py:726:
ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False …
```

Prevent an uncaught exception warning in a test suite thread

---

tests/middleware/test_asyncio.py

If `test_async_to_sync` runs immediately before `test_async_to_sync_no_thread`, the "no thread" test will fail to raise `RuntimeError` because the module-level `_event_loop_thread` variable will still be set (although it will be a mock, not a real thread).
This was discovered while trying to eliminate a different warning that only pops up if all of the asyncio tests are run; if only a handful of tests were selected, the warning disappears.
I strongly recommend adding pytest-randomly to the test suite's Python dependencies to help shake out test suite interdependencies such as what was found here.

Eliminate a test ordering dependency

---

tests/common.py
tests/test_rabbitmq.py
tox.ini

This PR addresses two additional issues with the test suite:
* The "cpython" factor listed in the tox environments conflicts with the "py3<X>" factors.
* Some RabbitMQ tests are not guarded by the implicit "skip" provided by the `rabbitmq_broker` fixture.
These two issues are now addressed, and the test suite can be run more easily.
I recommend modifying CI to execute tox directly; this will more closely align local test suite execution and CI runs.

Fix additional test suite issues

---

tox.ini

This PR enables all warnings in the test suite when run in tox.
With this change, additional `ResourceWarning` warnings display. For example:
```
sys:1: ResourceWarning: unclosed file <_io.BufferedRandom name='/tmp/dramatiq-prometheus/gauge_all_2653069.db'>
sys:1: ResourceWarning: unclosed file <_io.BufferedRandom name='/tmp/dramatiq-prometheus/gauge_livesum_2653069.db'>
sys:1: ResourceWarning: unclosed file <_io.BufferedRandom name='/tmp/dramatiq-prometheus/histogram_2653069.db'>
sys:1: ResourceWarning: unclosed file <_io.BufferedRandom name='/tmp/dramatiq-prometheus/counter_2653069.db'>
```
Through trial and error I was able to isolate these four open files to the following test (other tests in that file only trigger warnings about three or fewer unclosed files):
```
tox -e py38 -- …
```

Enable all Python warnings in the test suite

---

dramatiq/actor.py

Close https://github.com/Bogdanp/dramatiq/issues/640

feat: update actor_name assignment in decorator

---

dramatiq/middleware/retries.py
tests/middleware/test_retries.py

Hi 👋, 
small bugfix for the following issue that I stumbled over:
```python
@dramatiq.actor(max_retries=99)
def do_work():
raise Exception("attempt failed")
do_work.send_with_options(max_retries=0)
```
-> `do_work` will be retried 100 times instead of once, even though message options should override actor options.

Fix bug so `max_retries` can be overridden to zero in message options

---

CONTRIBUTORS.md
dramatiq/middleware/retries.py
tests/middleware/test_retries.py

E.g.,
```python
@dramatiq.actor
def on_abandon_flaky_work(message_data, retry_info):
logger.info("Too flaky, will not retry", message_data=message_data, retry_info=retry_info)
@dramatiq.actor(max_retries=5, on_retry_exhausted=on_abandon_flaky_work.actor_name)
def my_flaky_actor(*args, **kwargs):
do_flaky_work(*args, **kwargs)
```

Add callback for retry exhaustion

---

.github/workflows/push.yml
.github/workflows/release.yml
dramatiq/actor.py
dramatiq/middleware/time_limit.py
setup.py
tests/middleware/test_time_limit.py

`threading.Thread` received a new `_handle` attribute in Python 3.13, which clashes with dramatiq's `_CtypesTimeoutManager(Thread)` class. This commit renames the dramatiq method to resolve the conflict.
It also adds Python 3.13 to CI and package classification.

Fix #656 -- Add Python 3.13 support

---

dramatiq/cli.py

the `signum` received in the signal handler is an `int`, not a `Signals` object. this leads to errors like so:
```
[2024-11-12 16:49:05,288] [PID 151] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Stopping fork process...
res = self._popen.wait(timeout)
File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
return self.poll(os.WNOHANG if timeout == 0.0 else 0)
File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
pid, sts = os.waitpid(self.pid, flag)
File "/usr/local/lib/python3.10/site-packages/dramatiq/cli.py", line 579, in sighandler
logger.info("Sending signal %r to subprocesses...", getattr(signum, "name", signum))
File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
self._log(INFO, msg, args, **kwargs)
File …
```

fix: correct typing on signal handler

---

docs/source/advanced.rst

[As discussed on the mailing list](https://groups.io/g/dramatiq-users/message/311), this adds a link from the Dramatiq docs back to [dramatiq-workflow](https://github.com/Outset-AI/dramatiq-workflow).
Please let me know if you want different wording or move it to a different section! ❤️

Add dramatiq-workflow link

---

dramatiq/brokers/rabbitmq.py

fix: make sure RabbitMQ broker’s enqueue() attempts the correct number of preset retries

---

docs/source/cookbook.rst

Update sentry integration docs to refernece `sentry-sdk`
Previously, the docs referenced `sentry-dramatiq` that has been deprecated and merged into `sentry-python` (`sentry-sdk`)

Update sentry integration docs to refernece `sentry-sdk`

---

docs/source/changelog.rst

I believe `dramatiq_queue_prefetch` is per worker process, not per thread.
As per the source code https://github.com/Bogdanp/dramatiq/blob/b372f431ae40ff383a5b450dc37c8e5d5671bf49/dramatiq/worker.py#L41
And this comment https://github.com/Bogdanp/dramatiq/issues/392#issuecomment-815458472
This matches my testing where, when running with 2 threads, I needed to set `dramatiq_queue_prefetch=2` to make each thread process a message, but not to pre-fetch any extra ones.

Fix changelog entry for dramatiq_queue_prefetch

---

CONTRIBUTORS.md
dramatiq/brokers/rabbitmq.py

This PR fixes a bug when queues on the `broker` are flushed.
The old behavior was incorrect. It didn't flush delayed queues ending with `.DQ` and `.XQ` because the main queue was in the `self.queues_pending` variable (e.g. undeclared yet). We will have to ensure queues exist by declaring them first.
The new behavior doesn't require queues to be declared. If the purge fails and the RabbitMQ server closes the channel, it is recreated again, and the flushing continues.
This PR doesn't come with tests. I was not able to find them for the existing code. Based on that I didn't initiate the discussion as this is only useful in dev/tests environment.

Fix flushing of RabbitMQ queues

---

dramatiq/broker.py
tests/test_messages.py

Small change to improve developer experience with Dramatiq+Sentry and possibly any other error aggregation platform.
Currently error messages in Sentry look like this:
This is caused by the following code is responsible for formatting log params in Sentry: https://github.com/getsentry/sentry-python/blob/adcfa0f6abf8850f3b007bde609d0f943f621786/sentry_sdk/logger.py#L24-L32. Sentry has its reasons to do this - `__str__` is more lossy than `__repr__`, for example exceptions stringify to their arguments, losing their class name.
After this change MessageProxy repr looks as follows:
`<MessageProxy Message(queue_name='default', actor_name='actor_name', args=('arg',), kwargs={}, options={}, message_id='fe5511da-59ed-4b45-80f2-526d02c935fb', message_timestamp=1743773870061)>`
Existing logging …

Add repr to MessageProxy

---

.github/workflows/push.yml

Ubuntu 20.04 has been removed as a runner, see https://github.com/actions/runner-images/issues/11101

Update CI to use ubuntu 24.04

---

CONTRIBUTORS.md
dramatiq/actor.py
tests/test_actors.py

Fix TypeError when using decorator on a module-less function

---

dramatiq/watcher.py

These events are causing unnecessary restarts.
If a file is (first opened and then) closed without a write, No restart is needed.
Closes #654

Ignore FileClosedNoWriteEvent events in file watcher

---

dramatiq/common.py

Fixes compatibility issues with gevent 25.4.1, released 17th April 2025. See https://github.com/gevent/gevent/issues/2099
The issue caused dramatiq's gevent test suite to fail.

fix: join_queue implementation for compatibility with gevent 25.4.1

---

tests/middleware/test_retries.py

The `test_message_contains_requeue_time_after_retry`  test uses a min_backoff and max_backoff of 100ms. 
This should, in theory, ensure the requeue time is later, yet clock precision and the near-instantaneous nature of stubbed components might occasionally lead to the timestamps being identical.
This causes occasional errors like the one below, happening quite often in the CI:
```
=================================== FAILURES ===================================
________________ test_message_contains_requeue_time_after_retry ________________
stub_broker = <dramatiq.brokers.stub.StubBroker object at 0x7ff2f020ee30>
stub_worker = <dramatiq.worker.Worker object at 0x7ff2f0241060>
def test_message_contains_requeue_time_after_retry(stub_broker, stub_worker):
requeue_timestamps = [] …
```

fix: occasional test_message_contains_requeue_time_after_retry fails

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

I think the current issue template is being ignored by github.
This should make it work again.
Plus the config.yml should make github suggestion the discussion board when opening an issue.

Update issue templates

---

dramatiq/cli.py

The write_pipe never goes out of scope and so the last process's write_pipe is never closed by the watcher process, which results in a hang on read() from this pipe in log_watcher when the worker process is killed, and blocking all worker processes when their respective write pipe buffers are exhausted.

Close write_pipe after forking

---

dramatiq/broker.py
tests/test_broker.py

See: https://github.com/Bogdanp/dramatiq/issues/708

feature: log warning when middleware of a given type is added twice

---

docs/source/changelog.rst
dramatiq/middleware/__init__.py
setup.py
tests/test_broker.py

I applied the patch proposed in #345 to make the Prometheus middleware optional:
- prometheus-client is now an optional dependency
- The Prometheus middleware is only loaded if the prometheus_client is installed.
fixes #345

make Prometheus optional

---

dramatiq/middleware/prometheus.py

unused since 1ff83f576f82380a4df57e9da9d333913a72f839,
Looks like it was no accident - this change enabled middleware to define "main process forks" - https://github.com/Bogdanp/dramatiq/commit/1ff83f576f82380a4df57e9da9d333913a72f839#diff-73ebb8c3b1b4e359737d3c991b8945a4f07b784729b051ecaa3cc0843d903565R330-R332, see https://dramatiq.io/reference.html#dramatiq.Middleware.forks.

prometheus: remove unused LOCK_PATH

---

docs/source/changelog.rst
dramatiq/common.py
tests/test_rabbitmq.py

Closes #651
Currently, because the 'jittering' makes the `backoff` smaller, for the first attempt, the returned value will be smaller than `factor` - which is `min_backoff`. This is the bug reported.
My change here is to make the 'jittering' _increase_ the backoff, so it is never smaller than `factor` (`min_backoff`).
This implementation does mean there will be no jittering once max_backoff is reached.
Is that a problem? @Bogdanp Can I get your opinion?

Change `compute_backoff` implementation to respect min_backoff

---

docs/source/changelog.rst
dramatiq/results/middleware.py

Revisiting #332 
Change so that a Result backend must be provided when creating the `ResultMiddleware`.
Technically a breaking change, but v2 is planned to be the next release.
Previously, using the middleware with `backend=None` would be broken if you ever tried to store a result. So you could do that and never store a result, but that is sort of pointless.

Make `backend` a required argument to `ResultMiddleware`

---

docs/source/guide.rst
dramatiq/brokers/rabbitmq.py

Closes #724 
* Make limitations of Actor `priority` option clear. 
* Improve examples of RabbitMQ `broker_priority`.
* Link to the RabbitMQ `broker_priority` example from the guide.

Improve Documentation about message priorities

---

dramatiq/actor.py
dramatiq/broker.py
dramatiq/brokers/rabbitmq.py
dramatiq/brokers/redis.py
dramatiq/brokers/stub.py
dramatiq/cli.py
dramatiq/common.py
dramatiq/composition.py
dramatiq/encoder.py
dramatiq/errors.py
dramatiq/message.py
dramatiq/results/backend.py
dramatiq/results/backends/stub.py
dramatiq/worker.py
examples/issue_351/app.py

Closes #727
Adds a bunch of type annotations to many public functions; in two cases the annotations would require a minor rewrite of code itself.
I’ve not annotated `message` arguments because they can be either of type `Message` or `MessageProxy` (because they’re used interchangeably). I also refrained from importing modules guarded by `if TYPE_CHECKING` but I can add that too and further improve some method signatures. Please let me know what you prefer!

Improve typing coverage on external API, in particular Worker and Broker classes

---

dramatiq/broker.py

As discussed in comment https://github.com/Bogdanp/dramatiq/pull/735#discussion_r2228580283.

Adding a Middleware triggers the `after_declare_actor()` hook with the correct Actor parameter instead of the Actor’s name

---

dramatiq/message.py
tests/test_messages.py

Using divmod instead of floating point to avoid thinking about precision.
This feature is a trivial convenience that saves on having to check the docs to ensure that `datetime.utcfromtimestamp(message.message_timestamp / 1000)` is correct code.

Message.mesage_datetime property

---

dramatiq/middleware/middleware.py

Retry middleware code re-enqueueing the task: https://github.com/Bogdanp/dramatiq/blob/9037687d7c1ca1970acab525424f788fb24256fa/dramatiq/middleware/retries.py#L148
Brokers sending events:
https://github.com/Bogdanp/dramatiq/blob/9037687d7c1ca1970acab525424f788fb24256fa/dramatiq/brokers/redis.py#L193-L195
https://github.com/Bogdanp/dramatiq/blob/9037687d7c1ca1970acab525424f788fb24256fa/dramatiq/brokers/stub.py#L113-L115
https://github.com/Bogdanp/dramatiq/blob/9037687d7c1ca1970acab525424f788fb24256fa/dramatiq/brokers/rabbitmq.py#L365-L375

Document before/after_enqueue signals as including retries

---

dramatiq/brokers/stub.py
dramatiq/worker.py
tests/test_actors.py

I found this issue while working on #758
In `StubBroker.join()` when `message._exception` is None, we should fallback to an Exception.
This prevents errors like:
`TypeError: exceptions must derive from BaseException`
Either way an exception is raised, but this way it is an Exception with a nice message,
rather than TypeError.
Also fixes when Consumer handling a message gets `ActorNotFound` exception, store the Exception in the MessageProxy.
This means the exception is available to the `after_nack` middleware hook.
And available to the StubBroker to raise, when calling `.join(fail_fast=True)`

Fix edge case raising exception in `StubBroker.join()`

---

CONTRIBUTORS.md
docs/source/reference.rst
dramatiq/worker.py

This PR allows specifying the `dramatiq_worker_timeout` as an environment variable which is then passed into the worker. The goal for us was to be able to increase the `max_backoff` setting in `compute_backoff` with Redis because the default of 1000ms is too low for our use case.

add dramatiq_worker_timeout environment variable
